disabled_rules: # rule identifiers to exclude from running
  - large_tuple
  - line_length
  - function_parameter_count
  - nesting

identifier_name:
  excluded:
    - ak        # Access Key
    - dk        # Data Key
    - ef        # Encrypted Field
    - id        # ID

opt_in_rules:   # some rules are only opt-in
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - control_statement
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - file_header
  - file_length
  - first_where
  - force_unwrapping
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - no_extension_access_modifier
  - number_separator
  - object_literal
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefixed_toplevel_constant
  - private_action
  - prohibited_super_call
  - redundant_nil_coalescing
  - required_enum_case
  - sorted_first_last
  - sorted_imports
  - switch_case_on_newline
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - yoda_condition